# Generated by Django 2.1.dev20180118014615 on 2018-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
